#!/bin/bash
sum=0
n=0
for i in $*
do
if [ "$#" -ne 3 ]; then
    echo "You must enter exactly 3 command line arguments"
exit 1
fi
sum=`expr $sum + $i`
n=`expr $n + 1`
done
avg=`expr $sum / $n`
echo Average=$avg
