#!/bin/bash

echo -n "Enter the number day of week: "
read day

case $day in

  1)
    echo -n "Monday"
    ;;

  2)
    echo -n "Tuesday"
    ;;

  3)
    echo -n "Wednesday"
    ;;

  4)
    echo -n "Thursday"
    ;;

  5)
    echo -n "Friday"
    ;;

  6)
    echo -n "Saturday"
    ;;

  7)
    echo -n "Sunday"
    ;;

  *)
    echo -n "unknown"
    ;;
esac
